# Generated by Django 4.1.7 on 2023-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_test_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
