# Generated by Django 4.1.7 on 2023-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability_days',
            field=models.CharField(max_length=50),
        ),
    ]
